name: Deployment
on: 
  workflow_run:
    workflows:
      - Build
    branches:
      - main
    types:
      - completed

jobs:
  build:    
     runs-on: ubuntu-latest
     if: ${{ contains(github.ref, 'main') }}
     steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
        
      - name: display data
        shell: bash
        run: |
         echo ${{github.event.workflow_run.conclusion}}
         echo ${{github.event.workflow_run.id}}
         echo ${{github.event.workflow_run.runId}}
         echo ${{github.event.workflow_run.run_number}}
         echo ${{github.event.workflow_run.runnumber}}
         echo ${{github.event}}
         echo ${{github.event.workflow_run}}
         echo ${{github.event.workflow_run.buildId}}
         echo ${{github.event.workflow_run.buildid}}
        
