name: Deployment
on: 
  workflow_run:
    workflows:
      - Build
    branches:
      - main
    types:
      - completed

jobs:
  build:    
     runs-on: ubuntu-latest
     if: ${{ contains(github.ref, 'main') }}
     steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
          
      - shell: bash
        run: |
          echo ${{github.event.workflow_run.conclusion}} >> build-result.txt
          echo ${{github.event}} >> build-result.txt
          echo ${{github.event.workflow_run}} >> build-result.txt

      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build-result.txt
          
      - name: display data
        shell: bash
        run: |
         echo ${{github.event}}
         echo hello
         echo $github.event
         echo ${{github.event.workflow_run.conclusion}}
         echo $github.event.workflow_run.conclusion
         echo $github.event.workflow_run.id
        
