name: Deployment
on: 
  workflow_dispatch:
   inputs: 
     environment:
        type: choice
        description: Select the environment
        options:
        - dev
        - prod
        - test
        required: false
  workflow_run:
    workflows:
      - Build
    branches:
      - main
    types:
      - completed

jobs:
  build:    
     runs-on: ubuntu-latest
     if: ${{ contains(github.ref, 'main') }}
     steps:
      - uses: actions/checkout@v2
      - name: Set env
        if: |
          github.event.inputs.environment == ''
        run: echo "{ENVIRONMENT}={dev}" >> $GITHUB_ENV
        
      - name: Set env
        if: |
          github.event.inputs.environment == 'test'
        run: echo "{ENVIRONMENT}={test}" >> $GITHUB_ENV  
        
      - name: Test
        shell: bash
        run: |
          echo ${{ env.ENVIRONMENT }}
          echo $ENVIRONMENT
        
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
        
      - name: display data
        shell: bash
        run: |
         echo ${{github.event.workflow_run.conclusion}}
         echo ${{github.event.workflow_run.id}}
         echo ${{github.event.workflow_run.run_number}}
        
