name: Deployment
on: 
  workflow_dispatch:
   inputs: 
     environment:
        type: environment
        description: Select the environment
  workflow_run:
    workflows:
      - Build
    branches:
      - main
      - "release**"
    types:
      - completed

jobs:
  build:    
     runs-on: ubuntu-latest
     
     steps:
      - name: Set env
        if: |
          github.event.inputs.environment == ''
        run: |
          echo ${{github.ref_name}}
          echo ${{github.event.workflow_run.head_branch}}   
          echo "RUN_NUMBER=${{github.event.workflow_run.run_number}}" >> $GITHUB_ENV
          echo {{ env.RUN_NUMBER }}
          export runNumber="${{ github.event.workflow_run.run_number }}"
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          echo "RUN_NUMBER1=${runNumber}" >> $GITHUB_ENV
          echo {{ env.RUN_NUMBER1 }}
        
      - name: Set env
        if: |
          github.event.inputs.environment == 'test'
        run: echo "ENVIRONMENT=test" >> $GITHUB_ENV  
        
      - name: set Env
        id: setEnv
        run: |
          export ENVIRONMENT="${{ env.ENVIRONMENT }}"          
          echo "::set-output name=environment::${ENVIRONMENT}"
     outputs:
      environment: ${{ steps.setEnv.outputs.environment }}
  deploy:
     runs-on: ubuntu-latest
     needs: build
     steps:
      - uses: actions/checkout@v1          
      - name: dev
        if: ${{ needs.build.outputs.environment == ''}}
        shell: bash
        run: echo "Development"
       
      - name: test
        if: ${{ needs.build.outputs.environment == 'test'}}
        shell: bash
        run: echo "Release"
        
      
        
      - name: display data
        shell: bash
        run: |
         echo ${{ needs.build.outputs.environment }}
         echo ${{github.event.workflow_run.conclusion}}
         echo ${{github.event.workflow_run.id}}
         echo ${{github.event.workflow_run.run_number}}
        
