name: Deployment
on: 
  workflow_run:
    workflows:
      - Build
    branches:
      - main
    types:
      - completed

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'test') }}
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
 
