name: Deployment
on: 
  workflow_dispatch:
   inputs: 
     environment:
        type: environment
        description: Select the environment
  workflow_run:
    workflows:
      - Build
    branches:
      - main
    types:
      - completed

jobs:
  build:    
     runs-on: ubuntu-latest
     if: ${{ contains(github.ref, 'main') }}
     steps:
      - id: setEnv
      - uses: actions/checkout@v2
      - name: Set env
        if: |
          github.event.inputs.environment == ''
        run: echo "ENVIRONMENT=dev" >> $GITHUB_ENV
        
      - name: Set env
        if: |
          github.event.inputs.environment == 'test'
        run: echo "ENVIRONMENT=test" >> $GITHUB_ENV  
        
      - name: set Env
        shell: bash
        run: echo "::set-output name=environment::${env.ENVIRONMENT}"
        
  deploy:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v1          
      - name: dev
        if: ${{ steps.build.outputs.environment == ''}}
        shell: bash
        run: echo "Development"
       
      - name: test
        if: ${{ steps.build.outputs.environment == 'test'}}
        shell: bash
        run: echo "Release"
        
      
        
      - name: display data
        shell: bash
        run: |
         echo ${{github.event.workflow_run.conclusion}}
         echo ${{github.event.workflow_run.id}}
         echo ${{github.event.workflow_run.run_number}}
        
