name: Deployment
on: 
  workflow_dispatch:
   inputs: 
     environment:
        type: environment
        description: Select the environment
        options:
        - dev
        - test
        required: false
  workflow_run:
    workflows:
      - Build
    branches:
      - main
    types:
      - completed

jobs:
  build:    
     runs-on: ubuntu-latest
     if: ${{ contains(github.ref, 'main') }}
     steps:
      - name: set environment
        shell: bash
        run: |
          echo ${{ github.event.inputs.environment == ''  }}
          echo "choice is ${{ github.event.inputs.environment }}"
        
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
        
      - name: display data
        shell: bash
        run: |
         echo ${{github.event.workflow_run.conclusion}}
         echo ${{github.event.workflow_run.id}}
         echo ${{github.event.workflow_run.run_number}}
        
