name: Build
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
          
      - name: Comment Test Coverage
        uses: AthleticNet/comment-test-coverage@1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: coverage-summary.json
          title: Karma Test Coverage
       
      - name: Coverage report
        uses: eleboys/test-coverage-report-action@v1.0.2
        id: report
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: coverage-summary.json
          title: Karma Test Coverage

      - name: Print the output summary
        run: echo "Report coverage json ${{ steps.report.outputs.summary }}" 
